# labels to be used with /area command
area:
  - 'terraform'

kind:
  - 'documentation'
  - 'discussion'
  - 'feature'
  - 'question'

priority:
  - 'low'
  - 'medium'
  - 'high'
  - 'critical'

status:
  - available
  - blocked
  - in_progress
  - on_hold

# File globs for PR labeler
# tests:
#   - '**/*.test.ts'

'area/dns':
  - dns/**/*

'area/logging':
  - logging/**/*

'area/monitoring':
  - monitoring/**/*

'area/projects':
  - projects/**/*
